import Foundation

// Recipe: Clean old files from ~/Downloads on a schedule.
// IMPORTANT: Only deletes files (not directories) older than the threshold.
// Logs every deletion for safety.
struct CleanDownloadsRecipe: RecipeProvider {

    let type = RecipeType.cleanDownloads
    let name = "Clean Downloads"
    let triggerIcon = "clock"
    let actionIcon = "folder.badge.minus"
    let description = "Remove old files from your Downloads folder"
    let scriptKind = ScriptKind.shellScript

    let fields: [RecipeField] = [
        .numberField(label: "Delete files older than", placeholder: "30", unit: "days"),
        .timePicker(label: "Time"),
        .weekdayPicker(label: "Days"),
    ]

    func validate(config: [String: String]) -> String? {
        guard let daysStr = config["days"], let days = Int(daysStr), days > 0 else {
            return "Please enter a number of days (must be > 0)"
        }
        guard config["hour"] != nil, config["minute"] != nil else {
            return "Please set a time"
        }
        return nil
    }

    func generateScript(config: [String: String]) -> String {
        let days = config["days"] ?? "30"
        let logFile = FileLocations.logsDir.path + "/clean-downloads.log"
        // Only delete files (-type f), not directories
        // Log every deletion with timestamp
        return """
        #!/bin/bash
        # Clean Downloads — generated by Mac Automata
        # Only deletes FILES older than \(days) days. Directories are never touched.

        LOG_FILE="\(logFile)"
        DOWNLOADS="$HOME/Downloads"
        DAYS=\(days)

        echo "--- Clean run: $(date) ---" >> "$LOG_FILE"

        find "$DOWNLOADS" -maxdepth 1 -type f -mtime +$DAYS -print0 | while IFS= read -r -d '' file; do
            echo "Deleting: $file" >> "$LOG_FILE"
            rm "$file"
        done

        echo "Done." >> "$LOG_FILE"
        """
    }

    func sentence(config: [String: String]) -> String {
        let days = config["days"] ?? "30"
        let time = formatTime(config)
        let scheduleDays = formatDays(config)
        return "\(scheduleDays) at \(time), clean Downloads (files older than \(days) days)"
    }

    func scheduleDict(config: [String: String]) -> Any {
        return buildSchedule(config)
    }
}
