import Foundation

// Recipe: Open apps automatically when you log in.
// Uses launchd RunAtLoad — fires once when the agent is loaded at login.
struct LoginLaunchRecipe: RecipeProvider {

    let type = RecipeType.loginLaunch
    let name = "Launch at Login"
    let triggerIcon = "power"
    let actionIcon = "square.grid.2x2"
    let description = "Open apps automatically when you log in"
    let scriptKind = ScriptKind.shellScript

    let fields: [RecipeField] = [
        .appPicker(label: "Apps to open at login", multiple: true),
    ]

    func validate(config: [String: String]) -> String? {
        guard let apps = config["apps"], !apps.isEmpty else {
            return "Please select at least one app"
        }
        return nil
    }

    func generateScript(config: [String: String]) -> String {
        let apps = (config["apps"] ?? "").split(separator: ",").map(String.init)
        var lines = ["#!/bin/bash", "# Login launch — generated by Mac Automata",
                     "# Small delay to let the desktop finish loading",
                     "sleep 3"]
        for app in apps {
            let trimmed = app.trimmingCharacters(in: .whitespaces)
            lines.append("open -a \"\(trimmed)\"")
        }
        return lines.joined(separator: "\n")
    }

    func sentence(config: [String: String]) -> String {
        let apps = (config["apps"] ?? "").split(separator: ",").map {
            $0.trimmingCharacters(in: .whitespaces)
        }
        let appList = apps.isEmpty ? "apps" : apps.joined(separator: " and ")
        return "On login, open \(appList)"
    }

    func plistTriggerEntries(config: [String: String]) -> [String: Any] {
        return ["RunAtLoad": true]
    }
}
