import Foundation

// Recipe: Run an action when any external drive or volume is mounted.
// Uses launchd StartOnMount — fires when any volume is mounted (USB, SD card, etc.).
struct OnMountRecipe: RecipeProvider {

    let type = RecipeType.onMount
    let name = "On Drive Mount"
    let triggerIcon = "externaldrive.connected.to.line.below"
    let actionIcon = "square.grid.2x2"
    let description = "Open an app when you plug in an external drive"
    let scriptKind = ScriptKind.shellScript

    let fields: [RecipeField] = [
        .appPicker(label: "App to open", multiple: false),
    ]

    func validate(config: [String: String]) -> String? {
        guard let apps = config["apps"], !apps.isEmpty else {
            return "Please select an app"
        }
        return nil
    }

    func generateScript(config: [String: String]) -> String {
        let app = (config["apps"] ?? "").split(separator: ",").first
            .map { $0.trimmingCharacters(in: .whitespaces) } ?? ""
        return """
        #!/bin/bash
        # On mount — generated by Mac Automata
        open -a "\(app)"
        """
    }

    func sentence(config: [String: String]) -> String {
        let app = (config["apps"] ?? "").split(separator: ",").first
            .map { $0.trimmingCharacters(in: .whitespaces) } ?? "an app"
        return "When a drive is mounted, open \(app)"
    }

    func plistTriggerEntries(config: [String: String]) -> [String: Any] {
        return ["StartOnMount": true]
    }
}
