import Foundation

// Recipe: Open a specific file on a schedule.
// Works with any file type — audio, video, documents, images, etc.
// Uses the system default app for that file type via `open`.
struct OpenFileRecipe: RecipeProvider {

    let type = RecipeType.openFile
    let name = "Open File"
    let triggerIcon = "clock"
    let actionIcon = "doc.fill"
    let description = "Open any file (song, video, document) at a set time"
    let scriptKind = ScriptKind.shellScript

    let fields: [RecipeField] = [
        .filePicker(label: "File to open"),
        .timePicker(label: "Time"),
        .weekdayPicker(label: "Days"),
    ]

    func validate(config: [String: String]) -> String? {
        guard let filePath = config["filePath"], !filePath.isEmpty else {
            return "Please choose a file"
        }
        guard config["hour"] != nil, config["minute"] != nil else {
            return "Please set a time"
        }
        return nil
    }

    func generateScript(config: [String: String]) -> String {
        let filePath = config["filePath"] ?? ""
        return """
        #!/bin/bash
        # Open file — generated by Mac Automata
        open "\(filePath)"
        """
    }

    func sentence(config: [String: String]) -> String {
        let filePath = config["filePath"] ?? ""
        let fileName = (filePath as NSString).lastPathComponent
        let time = formatTime(config)
        let days = formatDays(config)
        let display = fileName.isEmpty ? "a file" : fileName
        return "\(days) at \(time), open \(display)"
    }

    func plistTriggerEntries(config: [String: String]) -> [String: Any] {
        return calendarTrigger(config)
    }
}
