import Foundation

// Recipe: Open one or more URLs in the default browser on a schedule.
struct OpenURLsRecipe: RecipeProvider {

    let type = RecipeType.openURLs
    let name = "Open URLs"
    let triggerIcon = "clock"
    let actionIcon = "globe"
    let description = "Open websites at a specific time"
    let scriptKind = ScriptKind.shellScript

    let fields: [RecipeField] = [
        .urlList(label: "URLs (one per line)"),
        .timePicker(label: "Time"),
        .weekdayPicker(label: "Days"),
    ]

    func validate(config: [String: String]) -> String? {
        guard let urls = config["urls"], !urls.isEmpty else {
            return "Please enter at least one URL"
        }
        guard config["hour"] != nil, config["minute"] != nil else {
            return "Please set a time"
        }
        return nil
    }

    func generateScript(config: [String: String]) -> String {
        let urls = (config["urls"] ?? "").split(separator: "\n").map {
            $0.trimmingCharacters(in: .whitespaces)
        }.filter { !$0.isEmpty }

        var lines = ["#!/bin/bash", "# Open URLs — generated by Mac Automata"]
        for url in urls {
            lines.append("open \"\(url)\"")
        }
        return lines.joined(separator: "\n")
    }

    func sentence(config: [String: String]) -> String {
        let urls = (config["urls"] ?? "").split(separator: "\n").map {
            $0.trimmingCharacters(in: .whitespaces)
        }.filter { !$0.isEmpty }
        let time = formatTime(config)
        let days = formatDays(config)
        let count = urls.count
        let noun = count == 1 ? "1 URL" : "\(count) URLs"
        return "\(days) at \(time), open \(noun)"
    }

    func scheduleDict(config: [String: String]) -> Any {
        return buildSchedule(config)
    }
}
