import Foundation

// Recipe: Open one or more apps on a schedule.
struct OpenAppsRecipe: RecipeProvider {

    let type = RecipeType.openApps
    let name = "Open Apps"
    let triggerIcon = "clock"
    let actionIcon = "square.grid.2x2"
    let description = "Launch apps at a specific time"
    let scriptKind = ScriptKind.shellScript

    let fields: [RecipeField] = [
        .appPicker(label: "Apps to open", multiple: true),
        .timePicker(label: "Time"),
        .weekdayPicker(label: "Days"),
    ]

    func validate(config: [String: String]) -> String? {
        guard let apps = config["apps"], !apps.isEmpty else {
            return "Please select at least one app"
        }
        guard config["hour"] != nil, config["minute"] != nil else {
            return "Please set a time"
        }
        return nil
    }

    func generateScript(config: [String: String]) -> String {
        let apps = (config["apps"] ?? "").split(separator: ",").map(String.init)
        var lines = ["#!/bin/bash", "# Open apps — generated by Mac Automata"]
        for app in apps {
            let trimmed = app.trimmingCharacters(in: .whitespaces)
            lines.append("open -a \"\(trimmed)\"")
        }
        return lines.joined(separator: "\n")
    }

    func sentence(config: [String: String]) -> String {
        let apps = (config["apps"] ?? "").split(separator: ",").map {
            $0.trimmingCharacters(in: .whitespaces)
        }
        let time = formatTime(config)
        let days = formatDays(config)
        let appList = apps.isEmpty ? "apps" : apps.joined(separator: " and ")
        return "\(days) at \(time), open \(appList)"
    }

    func scheduleDict(config: [String: String]) -> Any {
        return buildSchedule(config)
    }
}
