import Foundation

// Recipe: Watch a folder and move new files to another folder.
// Uses launchd WatchPaths — fires whenever the watched directory changes.
// Only moves files (not directories) to avoid breaking nested folder structures.
struct WatchAndMoveRecipe: RecipeProvider {

    let type = RecipeType.watchAndMove
    let name = "Watch Folder & Move"
    let triggerIcon = "eye"
    let actionIcon = "folder.badge.plus"
    let description = "When files appear in a folder, move them elsewhere"
    let scriptKind = ScriptKind.shellScript

    let fields: [RecipeField] = [
        .folderPicker(label: "Watch this folder", key: "sourceFolder"),
        .folderPicker(label: "Move files to", key: "destFolder"),
    ]

    func validate(config: [String: String]) -> String? {
        guard let source = config["sourceFolder"], !source.isEmpty else {
            return "Please choose a folder to watch"
        }
        guard let dest = config["destFolder"], !dest.isEmpty else {
            return "Please choose a destination folder"
        }
        if source == dest {
            return "Source and destination must be different folders"
        }
        return nil
    }

    func generateScript(config: [String: String]) -> String {
        let source = config["sourceFolder"] ?? ""
        let dest = config["destFolder"] ?? ""
        let logFile = FileLocations.logsDir.path + "/watch-move.log"
        return """
        #!/bin/bash
        # Watch & Move — generated by Mac Automata
        # Moves files (not directories) from source to destination.

        SOURCE="\(source)"
        DEST="\(dest)"
        LOG="\(logFile)"

        echo "--- Watch triggered: $(date) ---" >> "$LOG"

        # Create destination if it doesn't exist
        mkdir -p "$DEST"

        # Move only files (not directories, not hidden files)
        find "$SOURCE" -maxdepth 1 -type f -not -name '.*' -print0 | while IFS= read -r -d '' file; do
            filename=$(basename "$file")
            echo "Moving: $filename" >> "$LOG"
            mv "$file" "$DEST/$filename"
        done
        """
    }

    func sentence(config: [String: String]) -> String {
        let source = (config["sourceFolder"] as NSString?)?.lastPathComponent ?? "a folder"
        let dest = (config["destFolder"] as NSString?)?.lastPathComponent ?? "another folder"
        return "When files appear in \(source), move them to \(dest)"
    }

    func plistTriggerEntries(config: [String: String]) -> [String: Any] {
        let watchPath = config["sourceFolder"] ?? ""
        return ["WatchPaths": [watchPath]]
    }
}
